version: '3'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
    container_name: unknown-storage
  mysql:
    image: mysql:5.7
    volumes:
      - ./.docker/database/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      - storage
    ports:
      - "3306:3306"
    container_name: unknown-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
networks:
  default:
    external:
      name: unknown-network