version: '3'
services:
  app:
      build: ""
      volumes:
        - ./src:/var/opt/app
      environment:
        - "TZ=Japan"
        - "DB_HOST=unknown-db"
      container_name: unknown-web
networks:
  default:
    external:
      name: unknown-network