version: '3'
services:
  elixir: &defaults
    image: elixir:latest
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["mix"]
  iex:
    <<: *defaults
    entrypoint: ["iex"]
  mix:
    <<: *defaults
    entrypoint: ["mix"]
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
    container_name: unknown-storage
  mysql:
    image: mysql:5.6
    volumes:
      - storage
    ports:
      - "3306:3306"
    container_name: unknown-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"