version: '3'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
    container_name: cms-storage
  mysql:
    image: mysql:5.6
    volumes:
      - storage
    ports:
      - "3306:3306"
    container_name: cms-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  web:
    build: .
    volumes:
      - .:/var/opt/app
    environment:
      - "TZ=Japan"
    links:
      - mysql:mysql
    ports:
      - "4000:4000"
    container_name: cms-web
